CREATE DATABASE ABC;
USE ABC;

CREATE TABLE DEPT1 (
EMPID INT,
NAME VARCHAR(255),
ROLE VARCHAR(255)
);

INSERT INTO DEPT1 
VALUES (1, 'AMIT', 'ENGINEER'),
(2, 'SUMIT', 'SALESMAN'),
(3, 'PUNIT', 'MANAGER'),
(4, 'VISHWAJEET', 'SALESMAN'),
(5, 'GURUMEET', 'ENGINEER');

CREATE TABLE DEPT2 (
EMPID INT,
NAME VARCHAR(255),
ROLE VARCHAR(255)
);

INSERT INTO DEPT2
VALUES (3, 'PUNIT', 'MANAGER'),
(6, 'SURESH', 'MARKETING'),
(7, 'RAMESH', 'SALESMAN');

SELECT * FROM DEPT1
UNION
SELECT * FROM DEPT2;

SELECT * FROM DEPT1 WHERE ROLE = 'SALESMAN'
UNION
SELECT * FROM DEPT2 WHERE ROLE = 'SALESMAN';

SELECT DEPT1.* FROM DEPT1 INNER JOIN DEPT2 USING (EMPID);

SELECT DEPT1.* FROM DEPT1 LEFT JOIN DEPT2 USING (EMPID)
WHERE DEPT2.EMPID IS NULL;