USE temp;
CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
CNAME VARCHAR(255),
ADDRESS VARCHAR(255),
GENDER CHAR(2),
CITY VARCHAR(225),
PINCODE INTEGER
);

INSERT INTO CUSTOMER 
VALUES(6, 'ARPIT', 'CHAKKI NAKA', 'M', 'KALYAN', 421321);

INSERT INTO CUSTOMER (ID, CNAME, ADDRESS)
VALUES (7, 'BOBBY', 'CHOMU NAKA');

INSERT INTO CUSTOMER
VALUES (1, 'ROHIT', 'DHOKALI NAKA', 'M', 'THANE', 421306),
	   (2, 'ASHWINI', 'KOPRI NAKA', 'F', 'PUNE', 444215),
       (3, 'MOHIT', 'MANI NAKA', 'M', 'MUMBAI', 454156),
       (4, 'PRERNA', 'WAGHOLI NAKA', 'F', 'NAGPUR', 484654),
       (5, 'NAVNEET', 'TEMBHI NAKA', 'M', 'SATARA', 425648);
       
UPDATE CUSTOMER SET CNAME = 'CHINTU', ADDRESS = 'CHAMPI NAKA', GENDER = 'F' WHERE ID = 6;
SET SQL_SAFE_UPDATES = 0;
UPDATE CUSTOMER SET PINCODE = 444444;
UPDATE CUSTOMER SET PINCODE = PINCODE/6;
DELETE FROM CUSTOMER WHERE ID = 7;

DELETE FROM CUSTOMER;

REPLACE INTO CUSTOMER (ID, CITY)
VALUES(2, 'MUMBAI');

REPLACE INTO CUSTOMER (ID, CNAME)
VALUES(7, 'CODEHELP');

REPLACE INTO CUSTOMER (ID, CNAME, CITY)
VALUES(8, 'CODERWORLD', 'aagra');

-- OTHER SYNTAX OF REPLACE
REPLACE INTO CUSTOMER SET ID = 7, CNAME = 'PAWAN', CITY = 'KASHI';
REPLACE INTO CUSTOMER SET ID = 9, CNAME = 'LOVER', PINCODE = 420315;

REPLACE INTO CUSTOMER (ID, CNAME)
SELECT ID, CNAME
FROM CUSTOMER WHERE ID = 8;

SELECT * FROM CUSTOMER;
DROP TABLE CUSTOMER;
